// Display header

document.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">");

document.write("<div class=\"container\">");

document.write("<div class=\"navbar-header\" style=\"width: 100%; padding-top: 10px\">");

document.write("<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#menu\">");
document.write("<span class=\"sr-only\">Toggle navigation</span>");
document.write("<span class=\"icon-bar\"></span>");
document.write("<span class=\"icon-bar\"></span>");
document.write("<span class=\"icon-bar\"></span>");
document.write("</button>");

document.write("<div style=\"color: #FFFFFF; font-size: 24px; display: inline\">");
//document.write("<a class=\"desktop tablet\" href=\"http://www.toolstation.com/landing.html?r=misc&rr=NCEL\"><img src=\"/images/toolstation/lozenge.png\" style=\"height: 40px; padding-right: 10px\" align=\"left\"></a>");
//document.write("<a class=\"mobile\" href=\"http://www.toolstation.com/landing.html?r=misc&rr=NCEL\"><img src=\"/images/toolstation/lozenge.png\" style=\"height: 35px; padding-right: 10px\" align=\"left\"></a>");
document.write("<a class=\"desktop\" href=\"https://www.macron.com/uk\"><img src=\"/images/macron/macronverticalblack.png\" style=\"height: 60px; padding-right: 10px\" align=\"left\"></a>");
document.write("<a class=\"mobile tablet\" href=\"https://www.macron.com/uk\"><img src=\"/images/macron/macronverticalblack.png\" style=\"height: 40px; padding-right: 10px\" align=\"left\"></a>");
document.write("<font class=\"desktop\" style=\"color: #FFFFFF; font-size: 40px; font-family: Antonio\">NORTHERN COUNTIES EAST FOOTBALL LEAGUE</font>");
document.write("<font class=\"mobile tablet\" style=\"color: #FFFFFF; font-size: 20px; font-family: Antonio\">NCEL</font>");
document.write("<a class=\"desktop tablet\" href=\"/newsfeed.xml\"><img src=\"/images/social/RSS.png\" style=\"height: 30px; margin-top: 5px\" align=\"right\" title=\"NCEL RSS feed\"></a>");
document.write("<a class=\"desktop tablet\" href=\"https://www.youtube.com/@officialncel\"><img src=\"/images/social/YouTube.png\" style=\"height: 30px; margin-top: 5px; margin-right: 4px\" align=\"right\" title=\"NCEL on YouTube\"></a>");
document.write("<a class=\"desktop tablet\" href=\"https://bsky.app/profile/ncefl.org.uk\"><img src=\"/images/social/Bluesky.png\" style=\"height: 30px; margin-top: 5px; margin-right: 4px\" align=\"right\" title=\"NCEL on Bluesky\"></a>");
document.write("<a class=\"desktop tablet\" href=\"https://www.threads.net/@officialncel\"><img src=\"/images/social/Threads white on black.png\" style=\"height: 30px; margin-top: 5px; margin-right: 4px\" align=\"right\" title=\"NCEL on Threads\"></a>");
document.write("<a class=\"desktop tablet\" href=\"https://www.facebook.com/NorthernCountiesEastFootballLeague\"><img src=\"/images/social/Facebook.png\" style=\"height: 30px; margin-top: 5px; margin-right: 4px\" align=\"right\" title=\"NCEL on Facebook\"></a>");
document.write("<a class=\"desktop tablet\" href=\"https://www.instagram.com/officialncel/\"><img src=\"/images/social/Instagram.png\" style=\"height: 30px; margin-top: 5px; margin-right: 4px\" align=\"right\" title=\"NCEL on Instagram\"></a>");
document.write("<a class=\"desktop tablet\" href=\"https://twitter.com/NCEL\"><img src=\"/images/social/X.png\" style=\"height: 30px; margin-top: 5px; margin-right: 4px\" align=\"right\" title=\"NCEL on X\"></a>");
document.write("</div>");

document.write("</div>");

document.write("<div>");
document.write("<ul class=\"nav navbar-nav desktop collapse navbar-collapse\" id=\"menu\">");
document.write("<li><a href=\"/\">Home</a></li>");
document.write("<li><a href=\"/live/\">Live Scores</a></li>");
document.write("<li class=\"dropdown\">");
document.write("<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"/news/\">News");
document.write("<span class=\"caret\"></span></a>");
document.write("<ul class=\"dropdown-menu\">");
document.write("<li><a href=\"/news/latest/\">Latest</a></li>");
document.write("<li><a href=\"/news/fixtures/\">Fixtures</a></li>");
document.write("<li><a href=\"/news/league/\">League</a></li>");
document.write("<li><a href=\"/news/ncelpremierdivision/\">Premier Division</a></li>");
document.write("<li><a href=\"/news/nceldivisionone/\">Division One</a></li>");
document.write("<li><a href=\"/news/othercompetitions/\">Other Competitions</a></li>");
document.write("<li><a href=\"/news/matchreviews/\">Match Reviews</a></li>");
document.write("<li><a href=\"/news/transfers/\">Transfers</a></li>");
document.write("<li class=\"divider\"></li>");
document.write("<li class=\"dropdown-header\">Media</li>");
//document.write("<li><a href=\"/news/recast/\">NCEL TV on Recast</a></li>");
document.write("<li><a href=\"/news/podcast/\">NCEL Podcast</a></li>");
document.write("<li><a href=\"/news/matchvideos/\">Match Videos</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"dropdown\">");
document.write("<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Matches");
document.write("<span class=\"caret\"></span></a>");
document.write("<ul class=\"dropdown-menu\">");
document.write("<li><a href=\"/matches/day/\">By Day</a></li>");
document.write("<li><a href=\"/matches/week/\">By Week</a></li>");
document.write("<li><a href=\"/matches/month\">By Month</a></li>");
document.write("<li class=\"divider\"></li>");
document.write("<li><a href=\"/matches/ncelpremierdivision/\">Premier Division</a></li>");
document.write("<li><a href=\"/matches/ncelpremierdivisionplayoffs/\">Premier Division Play-Offs</a></li>");
document.write("<li><a href=\"/matches/nceldivisionone/\">Division One</a></li>");
document.write("<li><a href=\"/matches/nceldivisiononeplayoffs/\">Division One Play-Offs</a></li>");
document.write("<li><a href=\"/matches/ncelleaguecup/\">League Cup</a></li>");
document.write("<li class=\"divider\"></li>");
document.write("<li><a href=\"/matches/facup/\">FA Cup</a></li>");
document.write("<li><a href=\"/matches/favase/\">FA Vase</a></li>");
document.write("<li class=\"divider\"></li>");
//document.write("<li><a href=\"/matches/derbyshireseniorcup/\">Derbyshire Senior Cup</a></li>");
document.write("<li><a href=\"/matches/eastridingseniorcup/\">East Riding Senior Cup</a></li>");
document.write("<li><a href=\"/matches/lincolnshireseniortrophy/\">Lincolnshire Senior Trophy</a></li>");
document.write("<li><a href=\"/matches/northridingseniorcup/\">North Riding Senior Cup</a></li>");
document.write("<li><a href=\"/matches/nottsseniorcup/\">Notts Senior Cup</a></li>");
document.write("<li><a href=\"/matches/sheffieldhallamshireseniorcup/\">Sheffield & Hallamshire Senior Cup</a></li>");
document.write("<li><a href=\"/matches/westridingcountycup/\">West Riding County Cup</a></li>");
document.write("<li class=\"divider\"></li>");
document.write("<li><a href=\"/matches/friendlies/\">Friendlies</a></li>");
document.write("<li class=\"divider\"></li>");
document.write("<li><a href=\"/matches/fixturegrids/\">Fixture Grids</a></li>");
document.write("<li><a href=\"/matches/attendancegrids/\">Attendance Grids</a></li>"); 
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"dropdown\">");
document.write("<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"/tables/\">Tables");
document.write("<span class=\"caret\"></span></a>");
document.write("<ul class=\"dropdown-menu\">");
document.write("<li class=\"mobile\"><a href=\"/tables/long/\">Full</a></li>");
document.write("<li class=\"nomobile\"><a href=\"/tables/long/\">Long Version</a></li>");
document.write("<li class=\"nomobile\"><a href=\"/tables/short/\">Short Version</a></li>");
document.write("<li><a href=\"/tables/home/\">Home</a></li>");
document.write("<li><a href=\"/tables/away/\">Away</a></li>");
document.write("<li><a href=\"/tables/form/\">Form</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"dropdown\">");
document.write("<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Statistics");
document.write("<span class=\"caret\"></span></a>");
document.write("<ul class=\"dropdown-menu\">");
document.write("<li><a href=\"/statistics/topscorers/\">Top Scorers</a></li>");
document.write("<li><a href=\"/statistics/fairplayleague/\">David Morrall Fair Play League</a></li>");
document.write("<li class=\"divider\"></li>");
document.write("<li><a href=\"/statistics/ncelpremierdivision/\">Premier Division</a></li>");
document.write("<li><a href=\"/statistics/ncelpremierdivisionplayoffs/\">Premier Division Play-Offs</a></li>");
document.write("<li><a href=\"/statistics/nceldivisionone/\">Division One</a></li>");
document.write("<li><a href=\"/statistics/nceldivisiononeplayoffs/\">Division One Play-Offs</a></li>");
document.write("<li><a href=\"/statistics/ncelleaguecup/\">League Cup</a></li>");
document.write("<li class=\"divider\"></li>");
document.write("<li><a href=\"/statistics/facup/\">FA Cup</a></li>");
document.write("<li><a href=\"/statistics/favase/\">FA Vase</a></li>");
document.write("<li class=\"divider\"></li>");
//document.write("<li><a href=\"/statistics/derbyshireseniorcup/\">Derbyshire Senior Cup</a></li>");
document.write("<li><a href=\"/statistics/eastridingseniorcup/\">East Riding Senior Cup</a></li>");
document.write("<li><a href=\"/statistics/lincolnshireseniortrophy/\">Lincolnshire Senior Trophy</a></li>");
document.write("<li><a href=\"/statistics/northridingseniorcup/\">North Riding Senior Cup</a></li>");
document.write("<li><a href=\"/statistics/nottsseniorcup/\">Notts Senior Cup</a></li>");
document.write("<li><a href=\"/statistics/sheffieldhallamshireseniorcup/\">Sheffield & Hallamshire Senior Cup</a></li>");
document.write("<li><a href=\"/statistics/westridingcountycup/\">West Riding County Cup</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"dropdown\">");
document.write("<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Teams");
document.write("<span class=\"caret\"></span></a>");
document.write("<ul class=\"dropdown-menu\">");
document.write("<li><a href=\"/teams/ncelpremierdivision/\">Premier Division Teams</a></li>");
document.write("<li><a href=\"/teams/nceldivisionone/\">Division One Teams</a></li>");
document.write("<li><a href=\"/teams/map/\">Map</a></li>");
document.write("<li><a href=\"/teams/mileagegrid/\">Mileage Grid</a></li>");
document.write("<li><a href=\"/teams/former/\">Former Teams</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"dropdown\">");
document.write("<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Match Officials");
document.write("<span class=\"caret\"></span></a>");
document.write("<ul class=\"dropdown-menu\">");
document.write("<li><a href=\"/matchofficials/changes/\">Latest Changes</a></li>");
document.write("<li><a href=\"/matchofficials/appointments/\">Appointments</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"dropdown\">");
document.write("<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">League");
document.write("<span class=\"caret\"></span></a>");
document.write("<ul class=\"dropdown-menu\">");
document.write("<li><a href=\"/league/personnel/\">League Officials</a></li>");
document.write("<li><a href=\"/league/chaplain/\">League Chaplain</a></li>");
document.write("<li><a href=\"mailto:contactus@ncel.org.uk\">Contact Us</a></li>");
document.write("<li><a href=\"/league/rules/\">Rules</a></li>");
document.write("<li><a href=\"/league/handbooks/\">Handbooks</a></li>");
document.write("<li><a href=\"/league/downloads/\">Downloads</a></li>");
document.write("<li><a href=\"/league/honours/\">Honours</a></li>");
document.write("<li class=\"divider\"></li>");
document.write("<li class=\"dropdown-header\">Archive</li>");
document.write("<li><a href=\"/archive/newsletter/\">Newsletter</a></li>");
document.write("<li><a href=\"/archive/prencel/\">Pre-NCEL</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class=\"dropdown\">");
document.write("<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Links");
document.write("<span class=\"caret\"></span></a>");
document.write("<ul class=\"dropdown-menu\">");
document.write("<li><a href=\"/links/clublinks/\">Club Links</a></li>");
//document.write("<li><a href=\"/links/clubwebsites/\">Club Websites</a></li>");
//document.write("<li><a href=\"/links/clubtwitter/\">Clubs on X</a></li>");
//document.write("<li><a href=\"/links/clubfacebook/\">Clubs on Facebook</a></li>");
document.write("<li><a href=\"/links/other/\">Other Links</a></li>");
document.write("</ul>");
document.write("<li><a href=\"https://shop.ncefl.org.uk/\">Shop</a></li>");
document.write("</li>");
document.write("</ul>");
document.write("</div>");
document.write("</div>");
document.write("<div class=\"scrollmenu mobile\"><a href=\"/\">Home</a><a href=\"/live/\">Live Scores</a><a href=\"/news/\">News</a><a href=\"/matches/\">Matches</a><a href=\"/tables/\">Tables</a><a href=\"/statistics/topscorers/\">Top Scorers</a><a href=\"/statistics/ncelpremierdivision/\">Statistics</a><a href=\"/teams/\">Teams</a><a href=\"/matchofficials/\">Match Officials</a><a href=\"/league/personnel/\">League</a><a href=\"/links/clublinks/\">Links</a>");
document.write("<a href=\"https://shop.ncefl.org.uk/\">Shop</a></div>");
document.write("</nav>");